#!/usr/bin/env python3
from pathlib import Path
import hashlib
import json
import sys

ROOT = Path(__file__).resolve().parent
required = [
    ".github/workflows/apply-gen4-alpha1-panel-authority.yml",
    "tools/apply_gen4_alpha1.py",
    "payload_gen4/app/src/full/java/com/duoopen/shell/Fold7PanelAuthorityGen4.kt",
    "payload_gen4/app/src/test/java/com/duoopen/shell/Fold7PanelAuthorityGen4Test.kt",
    "APPLY_GEN4_ALPHA1_NOW.txt",
    "README_START_HERE_GEN4_ALPHA1.txt",
    "GEN4_ARCHITECTURE.md",
    "GEN4_RND_VALIDATION.txt",
    "GEN4_FIELD_TEST_CHECKLIST.md",
    "PRIMARY_AGENT_HANDOFF_GEN4_ALPHA1.txt",
    "PACKAGE_MANIFEST.json",
    "GEN4-SUPPORT-SHA256.txt",
]
for rel in required:
    if not (ROOT / rel).is_file():
        raise SystemExit(f"ERROR: missing {rel}")

manifest = json.loads((ROOT / "PACKAGE_MANIFEST.json").read_text())
assert manifest["baseline_main"] == "44f6d52abbf5de4cad36b0309b4d923d70f83d78"
assert manifest["target_runtime"] == "4.0.0-alpha1-zfold7"
assert manifest["target_version_code"] == 41

for line in (ROOT / "GEN4-SUPPORT-SHA256.txt").read_text().splitlines():
    if not line.strip():
        continue
    expected, rel = line.split("  ", 1)
    data = (ROOT / rel).read_bytes()
    actual = hashlib.sha256(data).hexdigest()
    if actual != expected:
        raise SystemExit(f"ERROR: checksum mismatch {rel}: {actual} != {expected}")

# No generated Python bytecode belongs in an audited transport bundle.
for path in ROOT.rglob("*"):
    if path.is_file() and (path.suffix == ".pyc" or "__pycache__" in path.parts):
        raise SystemExit(f"ERROR: generated bytecode present: {path.relative_to(ROOT)}")

print("GEN4 PACKAGE VALIDATION: PASS")
